dag:
  orders_dag_id: beam_pipeline_orders
  customers_dag_id: beam_pipeline_customers
  retries: 3
  retry_delay: 1  # minutes
  schedule_interval: "0 2 * * *"
  tags: ["beam", "etl"]

project:
  id: "~ENV_VAR:GCP_PROJECT_ID~"

gcs:
  source_bucket: "~ENV_VAR:GCS_SOURCE_BUCKET~"
  source_folder: input

bigquery:
  dataset: "~ENV_VAR:BQ_DATASET~"  

beam:
  orders_python_file: /home/airflow/gcs/dags/beam_pipeline_orders.py
  customers_python_file: /home/airflow/gcs/dags/beam_pipeline_customers.py
  temp_location: /tmp
  staging_location: /tmp/staging
  python_version: python3
  runner: DirectRunner
